### ISSUE TITLE
Questions regarding AutoInt attention_dim

### ISSUE THREAD

**Issue by abedshantti** [huawei-noah/benchmark#2]
Does the attention_dim feature in the implemented AutoInt model correspond to the number of hidden units `d'` in their paper? In section 5.1.4 of their [paper](https://dl.acm.org/doi/pdf/10.1145/3357384.3357925) they have set `d'` to 32. So I am wondering if this corresponds to `attention_dim = 8` in your [code](https://github.com/huawei-noah/benchmark/blob/5c58b721d845d0ded21ede5659c24ffaef132c75/FuxiCTR/fuxictr/pytorch/models/AutoInt.py#L28).

**Comment by zhujiem** [comment]
Yes, it should be. The hyper-parameter will be written in the model config.
